name: 'SuperPointNetBn'
descriptor_dim: &DIM 256
parameters:
  max_keypoints: 2048
  descriptor_dim: *DIM
  nms_kernel: 9
  remove_borders_size: 4
  keypoint_threshold: 0.005
  weights: '/home/ostap/projects/pytorch-superpoint/logs/superpoint_coco_heat2_0/checkpoints/superPointNet_170000_checkpoint.pth.tar'